/** @format */

import Head from 'next/head';
import FirstSection from '../components/First/FirstSection';
import Navbar from '../components/Nav/Navbar';
import SecondSection from '../components/Second/SecondSection';
import ThirdSection from '../components/Third/ThirdSection';
import FourthSection from '../components/Fourth/FourthSection';
import FifthSection from '../components/Fifth/FifthSection';
import SixthSection from '../components/Sixth/SixthSection';
import { MutableRefObject, useRef } from 'react';
import { Box, BoxTypeMap } from '@mui/material';
import LayoutComponent from '../components/LayoutComponent';
import { useMediaQuery } from '@mui/material';
import { createTheme, ThemeProvider } from '@material-ui/core/styles';
import styles from '/styles/Homes.module.scss';
import React from 'react';
import { Theme } from '@emotion/react';
import { OverridableComponent } from '@mui/material/OverridableComponent';

export default function Home() {
	const maxWidth1200 = useMediaQuery<string>('(max-width:1200px');
	const maxWidth900 = useMediaQuery<string>('(max-width:900px');
	const maxWidth600 = useMediaQuery<string>('(max-width:600px');

	const firstSectionRef =
		useRef<
			MutableRefObject<OverridableComponent<BoxTypeMap<{}, 'div'>> | null>
		>(null);
	const secondSectionRef = useRef<null | OverridableComponent<
		BoxTypeMap<{}, 'div'>
	>>(null);
	const thirdSectionRef = useRef<null | OverridableComponent<
		BoxTypeMap<{}, 'div'>
	>>(null);
	const fourthSectionRef = useRef<null | OverridableComponent<
		BoxTypeMap<{}, 'div'>
	>>(null);
	const fifthSectionRef = useRef<null | OverridableComponent<
		BoxTypeMap<{}, 'div'>
	>>(null);
	const sixthSectionRef = useRef<null | OverridableComponent<
		BoxTypeMap<{}, 'div'>
	>>(null);

	return (
		<>
			<Head>
				<title>Mechanical Shop</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Navbar
				firstSectionRef={firstSectionRef}
				secondSectionRef={secondSectionRef}
				thirdSectionRef={thirdSectionRef}
				fourthSectionRef={fourthSectionRef}
				fifthSectionRef={fifthSectionRef}
				sixthSectionRef={sixthSectionRef}
				maxWidth1200={maxWidth1200}
				maxWidth900={maxWidth900}
				maxWidth600={maxWidth600}
			/>
			<FirstSection
				myRef={firstSectionRef}
				maxWidth1200={maxWidth1200}
				maxWidth600={maxWidth600}
			/>
			<Box className={styles.layout}>
				<LayoutComponent
					myRef={secondSectionRef}
					maxWidth1200={maxWidth1200}
					maxWidth600={maxWidth600}
					title='About Us'>
					<SecondSection
						maxWidth1200={maxWidth1200}
						maxWidth600={maxWidth600}
					/>
				</LayoutComponent>
				<LayoutComponent
					myRef={thirdSectionRef}
					maxWidth1200={maxWidth1200}
					maxWidth600={maxWidth600}
					title='Offer'>
					<ThirdSection maxWidth1200={maxWidth1200} maxWidth600={maxWidth600} />
				</LayoutComponent>
				<LayoutComponent
					myRef={fourthSectionRef}
					maxWidth1200={maxWidth1200}
					maxWidth600={maxWidth600}
					title='Gallery'>
					<FourthSection maxWidth600={maxWidth600} />
				</LayoutComponent>
				<LayoutComponent
					myRef={fifthSectionRef}
					maxWidth1200={maxWidth1200}
					maxWidth600={maxWidth600}
					title='Recommendation'>
					<FifthSection maxWidth1200={maxWidth1200} maxWidth600={maxWidth600} />
				</LayoutComponent>
				<LayoutComponent
					myRef={sixthSectionRef}
					maxWidth1200={maxWidth1200}
					maxWidth600={maxWidth600}
					title='Contacts'>
					<SixthSection maxWidth1200={maxWidth1200} maxWidth600={maxWidth600} />
				</LayoutComponent>
			</Box>
		</>
	);
}
