/** @format */

import Head from 'next/head';
import FirstSection from '../components/First/FirstSection';
import Navbar from '../components/Nav/Navbar';
import SecondSection from '../components/Second/SecondSection';
import ThirdSection from '../components/Third/ThirdSection';
import FourthSection from '../components/Fourth/FourthSection';
import FifthSection from '../components/Fifth/FifthSection';
import SixthSection from '../components/Sixth/SixthSection';
import { useRef } from 'react';
import { Box } from '@mui/material';
import LayoutComp from '../components/LayoutComp';
import { useMediaQuery } from '@mui/material';
import { createTheme, ThemeProvider } from '@material-ui/core/styles';
import styles from '/styles/Homes.module.scss';

export default function Home() {
	const theme = createTheme({
		typography: {
			fontFamily: [
				'Orbitron, sans-serif',
				'Roboto',
				'Helvetica Neue',
				'Arial',
				'sans-serif'
			].join(',')
		}
	});

	const maxWidth1200 = useMediaQuery('(max-width:1200px');
	const maxWidth900 = useMediaQuery('(max-width:900px');
	const maxWidth600 = useMediaQuery('(max-width:600px');

	const myRef1 = useRef(null);
	const myRef2 = useRef(null);
	const myRef3 = useRef(null);
	const myRef4 = useRef(null);
	const myRef5 = useRef(null);
	const myRef6 = useRef(null);

	return (
		<>
			<ThemeProvider theme={theme}>
				<Head>
					<title>Mechanical Shop</title>
					<meta name='description' content='Generated by create next app' />
				</Head>
				<Navbar
					myRef1={myRef1}
					myRef2={myRef2}
					myRef3={myRef3}
					myRef4={myRef4}
					myRef5={myRef5}
					myRef6={myRef6}
					maxWidth1200={maxWidth1200}
					maxWidth900={maxWidth900}
					maxWidth600={maxWidth600}
				/>
				<FirstSection
					myRef={myRef1}
					maxWidth1200={maxWidth1200}
					maxWidth600={maxWidth600}
				/>
				<Box className={styles.layout}>
					<LayoutComp
						myRef={myRef2}
						maxWidth1200={maxWidth1200}
						maxWidth600={maxWidth600}
						title='About Us'>
						<SecondSection
							maxWidth1200={maxWidth1200}
							maxWidth900={maxWidth900}
							maxWidth600={maxWidth600}
						/>
					</LayoutComp>
					<LayoutComp
						myRef={myRef3}
						maxWidth1200={maxWidth1200}
						maxWidth600={maxWidth600}
						title='Offer'>
						<ThirdSection
							maxWidth1200={maxWidth1200}
							maxWidth900={maxWidth900}
							maxWidth600={maxWidth600}
						/>
					</LayoutComp>
					<LayoutComp
						myRef={myRef4}
						maxWidth1200={maxWidth1200}
						maxWidth600={maxWidth600}
						title='Gallery'>
						<FourthSection maxWidth600={maxWidth600} />
					</LayoutComp>
					<LayoutComp
						myRef={myRef5}
						maxWidth1200={maxWidth1200}
						maxWidth600={maxWidth600}
						title='Recommendation'>
						<FifthSection
							maxWidth1200={maxWidth1200}
							maxWidth600={maxWidth600}
						/>
					</LayoutComp>
					<LayoutComp
						myRef={myRef6}
						maxWidth1200={maxWidth1200}
						maxWidth600={maxWidth600}
						title='Contacts'>
						<SixthSection
							maxWidth1200={maxWidth1200}
							maxWidth600={maxWidth600}
						/>
					</LayoutComp>
				</Box>
			</ThemeProvider>
		</>
	);
}
